---
- name: Deploy AWS resources
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Determine student password
      ansible.builtin.set_fact:
        student_pswd: "{{ lookup('ansible.builtin.password', playbook_dir + '/student_password.txt', length=10, chars=['ascii_letters', 'digits']) }}"

    - name: Deploy AWS resources
      ansible.builtin.include_role:
        name: aws_ec2

- name: Configure QEMU
  hosts: hypervisor
  gather_facts: false
  become: true

  tasks:
    - name: Wait for instance to be up
      ansible.builtin.wait_for_connection:

    - name: Configure QEMU
      ansible.builtin.include_role:
        name: qemu

    - name: Configure ZTP elements
      ansible.builtin.include_role:
        name: ztp

- name: Install AAP
  hosts: all_ec2
  gather_facts: false
  become: true

  tasks:
    - name: Download and install containerized AAP
      ansible.builtin.include_role:
        name: aap
