---
- name: Configure network devices
  hosts: all

  vars:
    net_interfaces:
      - name: GigabitEthernet1
        description: Configured by Ansible

  tasks:
    - name: Set hostname to match inventory
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ inventory_hostname }}"
        state: merged

    - name: Set interface configs
      cisco.ios.ios_interfaces:
        config: "{{ net_interfaces }}"
        state: merged
