---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Fire on ztp endpoint events
      condition:
        all:
          - event.meta.endpoint == 'ztp'
      action:
        run_job_template:
          name: Standard network configuration
          organization: student{{ student }}
          job_args:
            limit: "{{ event.payload.serial_list }}"
