---
aws_security_rules:
  - proto: tcp
    ports: 22
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    ports: 443
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    ports: 9090
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    ports: 80
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    ports: 5000
    group_name: ansible
aws_ec2_name:
  hypervisor: hypervisor
  eda: eda
aws_ec2_type:
  hypervisor: c5n.metal
  eda: c5.large
aws_ec2_disk: 100
