---
- name: Wait for Controller to be available
  ansible.builtin.uri:
    url: https://{{ hostvars[groups.hypervisor.0]['public_dns'] }}/api/v2/ping/
    method: GET
    validate_certs: false
  register: _ping
  until: not _ping.failed
  run_once: true

- name: Get Controller token
  ansible.controller.token:
    description: EDA Controller
    scope: write
    controller_host: "{{ hostvars[groups.hypervisor.0]['public_dns'] }}"
    controller_username: admin
    controller_password: "{{ student_pswd | default('redhat') }}"
    validate_certs: false
  run_once: true

- name: Add config to EDA
  ansible.builtin.uri:
    url: https://{{ public_dns }}:{{ aap_eda_port }}/api/eda/v1/{{ item.endpoint }}/
    method: POST
    body_format: json
    body: "{{ item.payload }}"
    url_username: admin
    url_password: "{{ student_pswd | default('redhat') }}"
    validate_certs: false
    force_basic_auth: true
    status_code:
      - 201
      - 400
      - 409
  register: _eda_project
  changed_when: _eda_project.status == 201
  loop:
    - endpoint: projects
      payload:
        name: ZTP
        url: "{{ aap_repo }}"
    - endpoint: decision-environments
      payload:
        name: Supported RHEL9
        image_url: registry.redhat.io/ansible-automation-platform-24/de-supported-rhel9
    - endpoint: users/me/awx-tokens
      payload:
        name: admin
        token: "{{ controller_token.token }}"
