---
- name: Load student password for EDA hosts
  ansible.builtin.set_fact:
    student_pswd: "{{ hostvars.localhost.student_pswd | default('redhat') }}"
  when: inventory_hostname in groups.eda

- name: Install pre-requisite tasks
  ansible.builtin.include_tasks: prereqs.yml

- name: Install tasks
  ansible.builtin.include_tasks: install.yml

- name: Configure EDA
  ansible.builtin.include_tasks: eda_config.yml
  when: inventory_hostname in groups.eda
