---
- name: Install pre-requisite tasks
  ansible.builtin.include_tasks: prereqs.yml

- name: Install tasks
  ansible.builtin.include_tasks: install.yml

- name: Configure EDA
  ansible.builtin.include_tasks: eda_config.yml
